### PR TITLE
nonsense merge

### PR DESCRIPTION
**Pull request by markrosoft**

### CODE REVIEW

**Comment by markrosoft** [comment]
that was nonsense

**Comment by cdondrup** [comment]
At the moment if you commit something it will be shown as committed by "computing" because git thinks that this is your name. You should change this either globally for every commit from that PC:
1. `git config --global user.name "Your name"` Doesn't have to be your git username but can be your real name
2. `git config --global user.email me@mail.go` This has to be the email address you used when you registered with git
or you can just set these variables for the current repository you are working in:
1. cd to the repository on your machine
2. `git config --local user.name "Your name"` Doesnt have to be your git username but can be your real name
3. `git config --local user.email me@mail.go` This has to be the email address you used when you registered with git
If you commit something now, it be shown as your commit and not computing any longer.

**Comment by marc-hanheide** [comment]
thing is... that machine is used by different people and so is the directory. So, the better option is that with every commit you add `--author "Mark Collins <mark@markrosoft.org>"`, making the full command `git commit --author "Mark Collins <mark@markrosoft.org>" -m "explain what the commit is about here"`

**Comment by cdondrup** [comment]
If it is like that, than you're absolutely right. I just thought that we have two guys working on two computers and that there is no swapping of machines so I tried to suggest a more convenient solution. But the --author might be best in this case.

**Pull request closed without merging**
